server:
  port: 8087

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.metrics.tracing.enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.metrics.tracing.enabled: true

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:8743704615:AAHX9VRok3iHn-4m6FQGe8aO_2ClbJndLUU}

app:
  helpTree:
    api-url: ${HELPTREE_API_URL:http://localhost:8081}

logging:
  level:
    com.example.notificationservice: DEBUG
    io.micrometer.tracing: DEBUG
    io.opentelemetry: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %magenta([NOTIFY]) %X{traceId} %X{spanId} %X{requestId} %X{userId} %cyan(%logger{36}) - %msg%n"

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    mdc:
      field-names:
        - traceId
        - spanId
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
          protocol: http/protobuf
  endpoints:
    web:
      exposure:
        include: health,info,metrics,tracing
  endpoint:
    health:
      show-details: always


