server:
  port: 8080

spring:
  application:
    name: helpTree

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/helpTree_db}
    username: ${DB_USER:helpTree}
    password: ${DB_PASS:helpTree}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwtSecret: mySecretKeyForJWTGenerationWithAtLeast64CharactersLong12345678901234567890123456789012
  jwtExpirationMs: 86400000