server:
  port: 8080

spring:
  application:
    name: helpTree

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/helpTree_db}
    username: ${DB_USER:helpTree}
    password: ${DB_PASS:helpTree}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: helpEvent:org.example.helptreeservice.dto.HelpEvent
    template:
      default-topic: help-events


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    io.micrometer.tracing: DEBUG
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] traceId=%mdc{traceId} spanId=%mdc{spanId} %-5level %logger{36} - %msg%n"


app:
  jwtSecret: mySecretKeyForJWTGenerationWithAtLeast64CharactersLong12345678901234567890123456789012
  jwtExpirationMs: 86400000

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # в демо берём 100%, в production меньше (0.1, 0.01)
    propagation:
      type: w3c

    baggage:
      enabled: true
      correlation:
        enabled: true
        fields:
          - traceId
          - spanId
    otlp:
      tracing:
        endpoint: http://jaeger:4318/v1/traces

  info:
    env:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - loggers
          - prometheus

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

info:
  app:
    name: "HelpTree"
    version: "0.0.1"
    description: "My project"
